print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("How much tip would like to give? 10, 12, or 15? "))
bill_with_tip = int(input("How many people to split the bill? "))
result = round(bill*(1+tip/100)/bill_with_tip, 2)
print(f"Each person should pay: ${result}")
